language: c
jdk:
  - openjdk7
install: true
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
before_script:
- psql -c 'create database travis;' -U postgres
install:
- "./travis-tool.sh install_deps"
- "sudo R CMD javareconf"
- "./travis-tool.sh install_r yaml RJDBC RPostgreSQL testthat knitr devtools"
- "./travis-tool.sh install_github robertzk/testthatsomemore robertzk/berdie"
script: "echo $JAVA_HOME" # ./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
